### PR TITLE
Update libsvm specific version for DIIVINE Project

### PR DESCRIPTION
**Pull request by SuperBruceJia**
Dear all,

While I was reproducing the DIIVINE algorithm, I found that there were lots of errors w.r.t. the current libsvm package downloaded from `http://www.csie.ntu.edu.tw/~cjlin/libsvm/`. After hours of try, I have found that if we downloaded libsvm from this repo `https://github.com/gregfreeman/libsvm/tree/new_matlab_interface`, the algorithm could work well. 

That's why I hope you guys can update the link of the libsvm repo for the convenience of others. 

Thanks in advance and have a wonderful day!

Best,

Bruce Shuyue Jia

### CODE REVIEW

**Comment by JoshuaEbenezer** [comment]
Hi Bruce,
What kind of errors do you see? Is it because the version at https://www.csie.ntu.edu.tw/~cjlin/libsvm/ is not backwards-compatible?

**Comment by SuperBruceJia** [comment]
> Hi Bruce,
> What kind of errors do you see? Is it because the version at https://www.csie.ntu.edu.tw/~cjlin/libsvm/ is not backwards-compatible?

Hi, Joshua,

Thanks a lot for your reply.

Yep, I think the problem is caused by the incompatible version of the libsvm.

Please check the issue and error here: https://github.com/utlive/DIIVINE/issues/1.
(**I have closed the issue but it can always occur under the official libsvm version.**)

Best,

Bruce

**Comment by Lumos312** [comment]
> Dear all,
> 
> While I was reproducing the DIIVINE algorithm, I found that there were lots of errors w.r.t. the current libsvm package downloaded from `http://www.csie.ntu.edu.tw/~cjlin/libsvm/`. After hours of try, I have found that if we downloaded libsvm from this repo `https://github.com/gregfreeman/libsvm/tree/new_matlab_interface`, the algorithm could work well.
> 
> That's why I hope you guys can update the link of the libsvm repo for the convenience of others.
> 
> Thanks in advance and have a wonderful day!
> 
> Best,
> 
> Bruce Shuyue Jia

Hello, thank you for your advice. However, when I use the version of libsvm you provided, I still get the error you mentioned.Do you have any other ideas?
[Thank you for your reply.

**Comment by luoluoluo960** [comment]
Me too.

**Pull request closed without merging**
